// ROOT includes
#include <ROOT/RDataFrame.hxx>
#include <ROOT/RVec.hxx>
using ROOT::RDataFrame;
using ROOT::RDF::RNode;
using ROOT::VecOps::RVec;

// ROOT includes
#include <TFile.h>
#include <TTree.h>

#include <Math/Vector4D.h>
#include <Math/VectorUtil.h>
#include <cmath>
using LV = ROOT::Math::PtEtaPhiMVector;

// C++ includes
#include <iostream>
#include <string>
#include <regex>
#include <string>
#include <vector>

// ============================================================================
// Electron 2018 Loose Identification
// ============================================================================
auto elec_2018LooseID = [](const RVec<float>& Electron_pt,
                           const RVec<float>& Electron_eta,
                           const RVec<float>& Electron_deltaEtaSC,
                           const RVec<float>& Electron_dxy,
                           const RVec<float>& Electron_dz,
                           const RVec<float>& Electron_sip3d,
                           const RVec<float>& Electron_miniPFRelIso_all)
{
    const auto n = Electron_pt.size();
    RVec<bool> pass(n, 0);
    for (size_t i = 0; i < n; ++i)
    {
        if (not (std::fabs(Electron_eta[i] + Electron_deltaEtaSC[i]) < 2.5f)) continue;
        if (not (Electron_pt[i] > 10.0f)) continue;
        if (not (std::fabs(Electron_dxy[i]) < 0.05f)) continue;
        if (not (std::fabs(Electron_dz[i]) < 0.1f)) continue;
        if (not (std::fabs(Electron_sip3d[i]) < 8.0f)) continue;
        if (not (Electron_miniPFRelIso_all[i] < 0.4f)) continue;
        pass[i] = 1;
    }
    return pass;
};

std::vector<std::string> elec_2018LooseID_inputs =
{
    "Electron_pt",
    "Electron_eta",
    "Electron_deltaEtaSC",
    "Electron_dxy",
    "Electron_dz",
    "Electron_sip3d",
    "Electron_miniPFRelIso_all"
};

// ============================================================================
// Muon 2018 Loose Identification
// ============================================================================
auto muon_2018LooseID = [](const RVec<float>& Muon_pt,
                           const RVec<float>& Muon_eta,
                           const RVec<float>& Muon_dxy,
                           const RVec<float>& Muon_dz,
                           const RVec<float>& Muon_sip3d,
                           const RVec<float>& Muon_miniPFRelIso_all,
                           const RVec<bool>& Muon_looseId)
{
    const auto n = Muon_pt.size();
    RVec<bool> pass(n, 0);
    for (size_t i = 0; i < n; ++i)
    {
        if (not (Muon_pt[i] > 10.0f)) continue;
        if (not (std::fabs(Muon_eta[i]) < 2.4f)) continue;
        if (not (std::fabs(Muon_dxy[i]) < 0.05f)) continue;
        if (not (std::fabs(Muon_dz[i]) < 0.1f)) continue;
        if (not (std::fabs(Muon_sip3d[i]) < 8.0f)) continue;
        if (not (Muon_miniPFRelIso_all[i] < 0.4f)) continue;
        if (not (Muon_looseId[i])) continue;
        pass[i] = 1;
    }
    return pass;
};

std::vector<std::string> muon_2018LooseID_inputs =
{
    "Muon_pt",
    "Muon_eta",
    "Muon_dxy",
    "Muon_dz",
    "Muon_sip3d",
    "Muon_miniPFRelIso_all",
    "Muon_looseId"
};

// ============================================================================
// Jet 2018 ID Identification
// ============================================================================
auto jet_2018ID = [](const RVec<float>& Jet_pt,
                     const RVec<float>& Jet_eta,
                     const RVec<int>&   Jet_jetId)
{
    const auto n = Jet_pt.size();
    RVec<bool> pass(n, 0);

    for (size_t j = 0; j < n; ++j)
    {
        if (not (Jet_pt[j] >= 30.0f)) continue;
        if (not (std::fabs(Jet_eta[j]) <= 2.4f)) continue;
        if (not (Jet_jetId[j] >= 2)) continue;
        pass[j] = 1;
    }
    return pass;
};

std::vector<std::string> jet_2018ID_inputs =
{
    "Jet_pt",
    "Jet_eta",
    "Jet_jetId"
};

// ============================================================================
// GenParticle Filter
// ============================================================================
// ============================================================================
// GenParticle selection utilities (NanoAOD GenPart_* collection)
//
// Goal
//  1) Build a mask selecting particles that correspond (as closely as NanoAOD allows)
//     to the LHE hard-process record.
//  2) If a selected hard-process particle is W/Z/H/top/tau, also keep its full
//     decay tree as generated by Pythia (i.e. descendants), so you can read
//     W->cs, Z->bb, H->WW->..., H->ZZ->..., top->bW->..., tau decays, etc.
//  3) Return an RVec<bool> mask suitable for TrimCollection(..., maskCol, ...).
//
// Notes / assumptions
//  - NanoAOD does not store the LHE event record in GenPart; this uses GenPart
//    statusFlags to approximate "particles that would have been in LHE":
//      fromHardProcessBeforeFSR && isFirstCopy
//  - You can tune the "LHE-like" seed definition as needed.
// ============================================================================

inline auto gen_mask = [](const ROOT::VecOps::RVec<int>& pdgId,
                          const ROOT::VecOps::RVec<int>& status,
                          const ROOT::VecOps::RVec<int>& statusFlags,
                          const ROOT::VecOps::RVec<int>& genPartIdxMother) -> ROOT::VecOps::RVec<bool>
{
    using ROOT::VecOps::RVec;

    const size_t n = pdgId.size();
    RVec<bool> keep(n, false);
    if (n == 0) return keep;

    // status flags bit reader
    auto testBit = [](int flags, unsigned bit) -> bool {
        return (flags >> bit) & 0x1;
    };

    for (size_t i = 0; i < n; ++i)
    {
        const int s = status[i];
        const int p = pdgId[i];
        const int f = statusFlags[i];
        if (testBit(f, 7) and abs(p) <= 25) keep[i] = true;
        // std::cout <<  " s: " << s <<  " p: " << p <<  std::endl;
        // if (s == 21) keep[i] = true;
        // if (s == 23 and (abs(p) >= 11 and abs(p) <= 16)) keep[i] = true;
        // if (s == 23 and (abs(p) >= 1 and abs(p) <= 5)) keep[i] = true;
        // if (testBit(f, 8) and abs(p) <= 25) keep[i] = true;
        // if (s == 52) keep[i] = true;
        // keep[i] = true;
    }

    return keep;

};

inline std::vector<std::string> gen_mask_inputs =
{
    "GenPart_pdgId",
    "GenPart_status",
    "GenPart_statusFlags",
    "GenPart_genPartIdxMother"
};
// ==============================================================================






// -------------- ============ --------------------- ============ ---------------
// -------------- ============ --------------------- ============ ---------------
// -------------- ============ --------------------- ============ ---------------





// ============================================================================
// Object Properties Branches
// ============================================================================
inline std::vector<std::string> Muon_properties =
{
    "pt",
    "eta",
    "phi",
    "charge",
    "dxy",
    "dz",
    "sip3d",
    "miniPFRelIso_all"
};

inline std::vector<std::string> Electron_properties =
{
    "pt",
    "eta",
    "phi",
    "charge",
    "dxy",
    "dz",
    "sip3d",
    "miniPFRelIso_all"
};

inline std::vector<std::string> Jet_properties =
{
    "pt",
    "eta",
    "phi",
    "mass",
    "btagDeepFlavB"
};

inline std::vector<std::string> GenPart_properties =
{
    "pt",
    "eta",
    "phi",
    "mass",
    "pdgId",
    "status",
    "statusFlags",
    "genPartIdxMother",
};
// ==============================================================================






// -------------- ============ --------------------- ============ ---------------
// -------------- ============ --------------------- ============ ---------------
// -------------- ============ --------------------- ============ ---------------





// ==============================================================================
namespace RdfUtil
{

    // ============================================================================
    // Build a Good object collection from a NanoAOD style collection and a mask
    //
    // Purpose
    //   Create a filtered view of an object collection by applying a previously
    //   computed per object mask. The function defines new columns that follow
    //   a NanoAOD like naming convention such as
    //     GoodMuon_pt, GoodMuon_eta, GoodMuon_phi
    //   and also defines the corresponding multiplicity counter
    //     nGoodMuon
    //
    // Functional behavior
    //   For each requested branch suffix S in branchSuffixes
    //     outPrefix_S is defined as inPrefix_S[maskCol]
    //   and a counter nOutPrefix is defined as the number of true entries in maskCol
    //
    // Inputs
    //   inPrefix
    //     Collection prefix in the input tree such as Muon, Electron, Jet
    //
    //   maskCol
    //     Full name of the mask column such as Muon_2018LooseID
    //
    //   outPrefix
    //     Output collection prefix such as GoodMuon, GoodElectron, GoodJet
    //
    //   branchSuffixes
    //     List of branch suffixes to copy into the Good collection
    //
    // Outputs
    //   For each suffix S
    //     outPrefix_S
    //
    //   Counter
    //     nOutPrefix
    //
    // ============================================================================
    static RNode TrimCollection(RNode df,
                                const std::string& inPrefix,
                                const std::string& maskCol,
                                const std::string& outPrefix,
                                const std::vector<std::string>& branchSuffixes)
    {
        const std::string nOutCol = "n" + outPrefix;

        RNode out = df;

        for (std::size_t i = 0; i < branchSuffixes.size(); ++i)
        {
            const std::string& suf = branchSuffixes[i];

            const std::string inCol  = inPrefix + "_" + suf;
            const std::string outCol = outPrefix + "_" + suf;

            const std::string expr = inCol + "[" + maskCol + "]";
            out = out.Define(outCol, expr);
        }

        const std::string countExpr = "(int)Sum(" + maskCol + ")";
        out = out.Define(nOutCol, countExpr);

        return out;
    }


    // ============================================================================
    // Build a combined GoodLepton collection from GoodMuon and GoodElectron
    //
    // Purpose
    //   Merge previously built GoodMuon and GoodElectron collections into a single
    //   GoodLepton collection, sort by descending pt, and attach a per lepton pdgId
    //   consistent with charge and lepton flavor.
    //
    // Functional behavior
    //   For each event
    //     1) Concatenate GoodMuon and GoodElectron kinematics into one set
    //     2) Build pdgId using charge and flavor
    //        muon     pdgId = -13 if charge > 0 else +13
    //        electron pdgId = -11 if charge > 0 else +11
    //     3) Sort all leptons by pt in descending order
    //     4) Reorder all output branches consistently using the sort indices
    //     5) Define nGoodLepton following NanoAOD style naming
    //
    // Inputs
    //   GoodMuon_pt          RVec<float>
    //   GoodMuon_eta         RVec<float>
    //   GoodMuon_phi         RVec<float>
    //   GoodMuon_charge      RVec<int>
    //   GoodElectron_pt      RVec<float>
    //   GoodElectron_eta     RVec<float>
    //   GoodElectron_phi     RVec<float>
    //   GoodElectron_charge  RVec<int>
    //
    // Outputs
    //   GoodLepton_pt        RVec<float>
    //   GoodLepton_eta       RVec<float>
    //   GoodLepton_phi       RVec<float>
    //   GoodLepton_charge    RVec<int>
    //   GoodLepton_pdgId     RVec<int>
    //   GoodLepton_srcIdx    RVec<int>
    //   nGoodLepton          int
    //
    // Notes
    //   This helper assumes the GoodMuon and GoodElectron collections already exist
    //   and contain only leptons passing your intended IDs.
    // ============================================================================
    static RNode MergeCollections(RNode df,
                                  const std::string& goodObjectPrefix0,
                                  const std::string& goodObjectPrefix1,
                                  const std::string& outPrefix)
    {
        const std::string obj0_pt     = goodObjectPrefix0 + "_pt";
        const std::string obj0_eta    = goodObjectPrefix0 + "_eta";
        const std::string obj0_phi    = goodObjectPrefix0 + "_phi";
        const std::string obj0_charge = goodObjectPrefix0 + "_charge";

        const std::string obj1_pt     = goodObjectPrefix1 + "_pt";
        const std::string obj1_eta    = goodObjectPrefix1 + "_eta";
        const std::string obj1_phi    = goodObjectPrefix1 + "_phi";
        const std::string obj1_charge = goodObjectPrefix1 + "_charge";

        const std::string out_pt     = outPrefix + "_pt";
        const std::string out_eta    = outPrefix + "_eta";
        const std::string out_phi    = outPrefix + "_phi";
        const std::string out_charge = outPrefix + "_charge";
        const std::string out_pdgId  = outPrefix + "_pdgId";
        const std::string out_srcIdx = outPrefix + "_srcIdx";
        const std::string out_n      = "n" + outPrefix;

        const std::string carrier = "__" + outPrefix + "_carrier";

        struct GoodParticleCarrier {
            RVec<float> pt;
            RVec<float> eta;
            RVec<float> phi;
            RVec<int>   charge;
            RVec<int>   pdgId;
            RVec<int>   srcIdx;
        };

        RNode df1 =
            df.Define(
                carrier,
                [](const RVec<float>& Obj0_pt,
                   const RVec<float>& Obj0_eta,
                   const RVec<float>& Obj0_phi,
                   const RVec<int>&   Obj0_charge,
                   const RVec<float>& Obj1_pt,
                   const RVec<float>& Obj1_eta,
                   const RVec<float>& Obj1_phi,
                   const RVec<int>&   Obj1_charge) -> GoodParticleCarrier
                {
                    const size_t nobj0 = Obj0_pt.size();
                    const size_t nobj1 = Obj1_pt.size();
                    const size_t n     = nobj0 + nobj1;

                    GoodParticleCarrier out;
                    out.pt.resize(n);
                    out.eta.resize(n);
                    out.phi.resize(n);
                    out.charge.resize(n);
                    out.pdgId.resize(n);
                    out.srcIdx.resize(n);

                    size_t k = 0;

                    for (size_t i = 0; i < nobj0; ++i)
                    {
                        out.pt[k]     = Obj0_pt[i];
                        out.eta[k]    = Obj0_eta[i];
                        out.phi[k]    = Obj0_phi[i];
                        out.charge[k] = Obj0_charge[i];
                        out.srcIdx[k] = i;

                        const int q = (Obj0_charge[i] > 0.0f) ? +1 : -1;
                        out.pdgId[k] = (q > 0) ? -13 : +13;

                        ++k;
                    }

                    for (size_t i = 0; i < nobj1; ++i)
                    {
                        out.pt[k]     = Obj1_pt[i];
                        out.eta[k]    = Obj1_eta[i];
                        out.phi[k]    = Obj1_phi[i];
                        out.charge[k] = Obj1_charge[i];
                        out.srcIdx[k] = i;

                        const int q = (Obj1_charge[i] > 0.0f) ? +1 : -1;
                        out.pdgId[k] = (q > 0) ? -11 : +11;

                        ++k;
                    }

                    std::vector<size_t> idx(n);
                    for (size_t i = 0; i < n; ++i) idx[i] = i;

                    std::sort(idx.begin(), idx.end(),
                              [&out](size_t a, size_t b) { return out.pt[a] > out.pt[b]; });

                    GoodParticleCarrier sorted;
                    sorted.pt.resize(n);
                    sorted.eta.resize(n);
                    sorted.phi.resize(n);
                    sorted.charge.resize(n);
                    sorted.pdgId.resize(n);
                    sorted.srcIdx.resize(n);

                    for (size_t i = 0; i < n; ++i)
                    {
                        const size_t s = idx[i];
                        sorted.pt[i]     = out.pt[s];
                        sorted.eta[i]    = out.eta[s];
                        sorted.phi[i]    = out.phi[s];
                        sorted.charge[i] = out.charge[s];
                        sorted.pdgId[i]  = out.pdgId[s];
                        sorted.srcIdx[i] = out.srcIdx[s];
                    }

                    return sorted;
                },
                {obj0_pt, obj0_eta, obj0_phi, obj0_charge,
                    obj1_pt, obj1_eta, obj1_phi, obj1_charge});

        RNode df2 =
            df1.Define(out_pt    , [](const GoodParticleCarrier& c) -> RVec<float> { return c.pt; }, {carrier})
            .Define(out_eta   , [](const GoodParticleCarrier& c) -> RVec<float> { return c.eta; }, {carrier})
            .Define(out_phi   , [](const GoodParticleCarrier& c) -> RVec<float> { return c.phi; }, {carrier})
            .Define(out_charge, [](const GoodParticleCarrier& c) -> RVec<int> { return c.charge; }, {carrier})
            .Define(out_pdgId , [](const GoodParticleCarrier& c) -> RVec<int> { return c.pdgId; }, {carrier})
            .Define(out_srcIdx, [](const GoodParticleCarrier& c) -> RVec<int> { return c.srcIdx; }, {carrier})
            .Define(out_n     , [](const GoodParticleCarrier& c) -> int { return static_cast<int>(c.pt.size()); }, {carrier});

        return df2;
    }

    // ============================================================================
    // Overlap removal by deltaR against a reference collection
    //
    // Purpose
    //   Remove objects from a source collection if they overlap with any object in
    //   a reference collection within a configurable deltaR threshold. The output
    //   is a new collection containing only non overlapping objects and a NanoAOD
    //   style multiplicity counter.
    //
    // Functional behavior
    //   For each event, build a per object overlap mask for the source collection.
    //   A source object is rejected if there exists at least one reference object
    //   with deltaR(source, reference) < dR. The mask is then used to project the
    //   requested source branches into a new OR collection.
    //
    // Inputs
    //   Source collection columns
    //     srcPrefix_pt
    //     srcPrefix_eta
    //     srcPrefix_phi
    //   Reference collection columns
    //     refPrefix_eta
    //     refPrefix_phi
    //
    // Outputs
    //   A mask column
    //     outPrefix_ORmask
    //   A projected overlap removed collection
    //     outPrefix_suffix for each suffix in srcBranchSuffixes
    //   A multiplicity counter
    //     nOutPrefix
    //
    // Notes
    //   This helper is intended to be used after you have already created Good
    //   collections. It is generic for jets, leptons, photons, etc, as long as the
    //   collections use NanoAOD style eta and phi columns.
    // ============================================================================
    static RNode TrimCollectionByDeltaR(RNode df,
                                        const std::string& srcPrefix,
                                        const std::string& refPrefix,
                                        const std::string& outPrefix,
                                        const std::vector<std::string>& srcBranchSuffixes,
                                        const float dR)
    {
        const std::string srcEta = srcPrefix + "_eta";
        const std::string srcPhi = srcPrefix + "_phi";

        const std::string refEta = refPrefix + "_eta";
        const std::string refPhi = refPrefix + "_phi";

        const std::string maskCol = outPrefix + "_ORmask";

        const std::string nOutCol = "n" + outPrefix;

        // Build overlap mask for the source collection
        RNode df1 =
            df.Define(
                maskCol,
                [dR](const RVec<float>& sEta,
                     const RVec<float>& sPhi,
                     const RVec<float>& rEta,
                     const RVec<float>& rPhi) -> RVec<bool>
                {
                    const size_t ns = sEta.size();
                    const size_t nr = rEta.size();

                    RVec<bool> keep(ns, true);

                    for (size_t i = 0; i < ns; ++i)
                    {
                        bool overlaps = false;

                        for (size_t j = 0; j < nr; ++j)
                        {
                            LV p4_0(1, sEta[i], sPhi[i], 0);
                            LV p4_1(1, rEta[j], rPhi[j], 0);

                            float this_dr = ROOT::Math::VectorUtil::DeltaR(p4_0, p4_1);

                            if (this_dr < dR)
                            {
                                overlaps = true;
                                break;
                            }
                        }

                        if (overlaps) keep[i] = false;
                    }

                    return keep;
                },
                {srcEta, srcPhi, refEta, refPhi});

        // Project masked source branches into the overlap removed output collection
        RNode out = df1;

        for (std::size_t i = 0; i < srcBranchSuffixes.size(); ++i)
        {
            const std::string& suf = srcBranchSuffixes[i];

            const std::string inCol  = srcPrefix + "_" + suf;
            const std::string outCol = outPrefix + "_" + suf;

            const std::string expr = inCol + "[" + maskCol + "]";
            out = out.Define(outCol, expr);
        }

        // Define NanoAOD style multiplicity counter for the OR collection
        const std::string countExpr = "(int)Sum(" + maskCol + ")";
        out = out.Define(nOutCol, countExpr);

        return out;
    }

    // ===============================================================================
    //   Utility helpers for programmatic column selection in ROOT RDataFrame
    //   pipelines.
    // 
    //   Motivation:
    //     RDataFrame::Snapshot() does not support wildcard or glob-based column
    //     selection. This header provides a deterministic, zero-runtime-overhead
    //     mechanism to select Snapshot output columns using Unix-style glob patterns.
    // 
    //   Supported glob syntax:
    //       *    matches any number of characters (including zero)
    //       ?    matches exactly one character
    // 
    //   Features:
    //     - Include and exclude glob filters
    //     - Deterministic ordering
    //     - Thread-safe
    //     - No duplicates
    //     - Evaluated once at graph-construction time (no per-event cost)
    // 
    //   Example:
    //       auto cols = SelectColumnNames(df,
    //           { "GoodMuon_*", "GoodElectron_*", "GoodLepton_*", "MET_*" },
    //           { "*_ord", "*_srcIdx", "*_isMuon", "*_tmp*" });
    // 
    //       df.Snapshot("Events", "analysis.root", cols);
    // 
    // ===============================================================================


    inline std::regex GlobToRegex(const std::string& glob)
    {
        std::string r;
        r.reserve(glob.size() * 2);
        r.push_back('^');

        for (char c : glob) {
            switch (c) {
                case '*': r += ".*"; break;
                case '?': r += "."; break;
                case '.': case '\\': case '+': case '^': case '$':
                case '(': case ')': case '{': case '}': case '[': case ']':
                case '|':
                          r.push_back('\\'); r.push_back(c); break;
                default:
                          r.push_back(c);
            }
        }
        r.push_back('$');
        return std::regex(r, std::regex::ECMAScript);
    }


    inline std::vector<std::string> SelectColumnNames(ROOT::RDF::RNode df,
                                                               const std::vector<std::string>& include,
                                                               const std::vector<std::string>& exclude = {})
    {
        const auto all = df.GetColumnNames();

        std::vector<std::regex> inc, exc;
        for (auto& g : include) inc.emplace_back(GlobToRegex(g));
        for (auto& g : exclude) exc.emplace_back(GlobToRegex(g));

        std::vector<std::string> out;
        out.reserve(all.size());

        for (const auto& c : all) {
            bool keep = false;

            for (const auto& r : inc)
                if (std::regex_match(c, r)) { keep = true; break; }

            if (!keep) continue;

            for (const auto& r : exc)
                if (std::regex_match(c, r)) { keep = false; break; }

            if (keep) out.push_back(c);
        }

        return out;
    }


    // ============================================================================
    // MatchCollection: attach gen-match results to an existing lepton collection
    //
    // Behavior
    //   - For each lepton, match to the closest gen *lepton* (|pdgId| in {11,13,15})
    //     within ΔR < dRMax.
    //   - Always defines these three branches:
    //       lepPrefix_goodGenPartIdx
    //       lepPrefix_goodGenPartDr
    //       lepPrefix_goodGenPartPdgId
    //
    // Inputs required
    //   lepPrefix_eta, lepPrefix_phi
    //   genPrefix_eta, genPrefix_phi, genPrefix_pdgId
    //
    // Output indexing
    //   idx points into the *trimmed* gen collection (e.g. GoodGenPart_*).
    // ============================================================================
    static ROOT::RDF::RNode MatchCollection(ROOT::RDF::RNode df,
                                            const std::string& lepPrefix,
                                            const std::string& genPrefix,
                                            const float dRMax)
    {
        using ROOT::VecOps::RVec;

        // Named carrier type (must be visible to ROOT's type introspection)
        struct GenMatchCarrier
        {
            ROOT::VecOps::RVec<int>   idx;   // index into genPrefix collection
            ROOT::VecOps::RVec<float> dr;    // best ΔR (inf if none)
            ROOT::VecOps::RVec<int>   pdgId; // matched gen pdgId (0 if none)
        };

        const std::string lep_eta = lepPrefix + "_eta";
        const std::string lep_phi = lepPrefix + "_phi";

        const std::string gen_eta = genPrefix + "_eta";
        const std::string gen_phi = genPrefix + "_phi";
        const std::string gen_pdg = genPrefix + "_pdgId";

        const std::string carrier = "__" + lepPrefix + "_genMatchCarrier";

        const std::string out_idx = lepPrefix + "_goodGenPartIdx";
        const std::string out_dr  = lepPrefix + "_goodGenPartDr";
        const std::string out_pdg = lepPrefix + "_goodGenPartPdgId";

        auto absId = [](int x) { return x < 0 ? -x : x; };

        // Build carrier (explicit types, explicit return type)
        df = df.Define(
            carrier,
            [dRMax, absId](const RVec<float>& lEta,
                          const RVec<float>& lPhi,
                          const RVec<float>& gEta,
                          const RVec<float>& gPhi,
                          const RVec<int>&   gPdg) -> GenMatchCarrier
            {
                const size_t nl = lEta.size();
                const size_t ng = gEta.size();

                GenMatchCarrier out;
                out.idx.assign(nl, -1);
                out.dr.assign(nl, std::numeric_limits<float>::infinity());
                out.pdgId.assign(nl, 0);

                auto isGenLepton = [&](int pdgId) {
                    const int a = absId(pdgId);
                    return (a == 11) || (a == 13) || (a == 15);
                };

                for (size_t i = 0; i < nl; ++i)
                {
                    float best = dRMax;
                    int bestIdx = -1;

                    LV p4l(1.0, lEta[i], lPhi[i], 0.0);

                    for (size_t j = 0; j < ng; ++j)
                    {
                        if (!isGenLepton(gPdg[j])) continue;

                        LV p4g(1.0, gEta[j], gPhi[j], 0.0);
                        const float dr = ROOT::Math::VectorUtil::DeltaR(p4l, p4g);

                        if (dr < best)
                        {
                            best = dr;
                            bestIdx = (int)j;
                        }
                    }

                    if (bestIdx >= 0)
                    {
                        out.idx[i]  = bestIdx;
                        out.dr[i]   = best;
                        out.pdgId[i]= gPdg[bestIdx];
                    }
                }

                return out;
            },
            {lep_eta, lep_phi, gen_eta, gen_phi, gen_pdg}
        );

        // Unpack carrier (explicit lambdas; no generic lambdas)
        df = df.Define(out_idx, [](const GenMatchCarrier& c) -> RVec<int> { return c.idx; }, {carrier});
        df = df.Define(out_dr, [](const GenMatchCarrier& c) -> RVec<float> { return c.dr; }, {carrier});
        df = df.Define(out_pdg, [](const GenMatchCarrier& c) -> RVec<int> { return c.pdgId; }, {carrier});

        return df;
    }
}



