// ROOT includes
#include <ROOT/RDataFrame.hxx>
#include <ROOT/RVec.hxx>
using ROOT::RDataFrame;
using ROOT::RDF::RNode;
using ROOT::VecOps::RVec;

// ROOT includes
#include <TFile.h>
#include <TTree.h>

#include <Math/Vector4D.h>
#include <Math/VectorUtil.h>
#include <cmath>
using LV = ROOT::Math::PtEtaPhiMVector;

// C++ includes
#include <iostream>
#include <string>
#include <regex>
#include <string>
#include <vector>

// ============================================================================
// Electron 2018 Loose Identification
// ============================================================================
auto elec_2018LooseID = [](const RVec<float>& Electron_pt,
                           const RVec<float>& Electron_eta,
                           const RVec<float>& Electron_deltaEtaSC,
                           const RVec<float>& Electron_dxy,
                           const RVec<float>& Electron_dz,
                           const RVec<float>& Electron_sip3d,
                           const RVec<float>& Electron_miniPFRelIso_all)
{
    const auto n = Electron_pt.size();
    RVec<bool> pass(n, 0);
    for (size_t i = 0; i < n; ++i)
    {
        if (not (std::fabs(Electron_eta[i] + Electron_deltaEtaSC[i]) < 2.5f)) continue;
        if (not (Electron_pt[i] > 10.0f)) continue;
        if (not (std::fabs(Electron_dxy[i]) < 0.05f)) continue;
        if (not (std::fabs(Electron_dz[i]) < 0.1f)) continue;
        if (not (std::fabs(Electron_sip3d[i]) < 8.0f)) continue;
        if (not (Electron_miniPFRelIso_all[i] < 0.4f)) continue;
        pass[i] = 1;
    }
    return pass;
};

std::vector<std::string> elec_2018LooseID_inputs =
{
    "Electron_pt",
    "Electron_eta",
    "Electron_deltaEtaSC",
    "Electron_dxy",
    "Electron_dz",
    "Electron_sip3d",
    "Electron_miniPFRelIso_all"
};

// ============================================================================
// Muon 2018 Loose Identification
// ============================================================================
auto muon_2018LooseID = [](const RVec<float>& Muon_pt,
                           const RVec<float>& Muon_eta,
                           const RVec<float>& Muon_dxy,
                           const RVec<float>& Muon_dz,
                           const RVec<float>& Muon_sip3d,
                           const RVec<float>& Muon_miniPFRelIso_all,
                           const RVec<bool>& Muon_looseId)
{
    const auto n = Muon_pt.size();
    RVec<bool> pass(n, 0);
    for (size_t i = 0; i < n; ++i)
    {
        if (not (Muon_pt[i] > 10.0f)) continue;
        if (not (std::fabs(Muon_eta[i]) < 2.4f)) continue;
        if (not (std::fabs(Muon_dxy[i]) < 0.05f)) continue;
        if (not (std::fabs(Muon_dz[i]) < 0.1f)) continue;
        if (not (std::fabs(Muon_sip3d[i]) < 8.0f)) continue;
        if (not (Muon_miniPFRelIso_all[i] < 0.4f)) continue;
        if (not (Muon_looseId[i])) continue;
        pass[i] = 1;
    }
    return pass;
};

std::vector<std::string> muon_2018LooseID_inputs =
{
    "Muon_pt",
    "Muon_eta",
    "Muon_dxy",
    "Muon_dz",
    "Muon_sip3d",
    "Muon_miniPFRelIso_all",
    "Muon_looseId"
};

// ============================================================================
// Jet 2018 ID Identification
// ============================================================================
auto jet_2018ID = [](const RVec<float>& Jet_pt,
                     const RVec<float>& Jet_eta,
                     const RVec<int>&   Jet_jetId)
{
    const auto n = Jet_pt.size();
    RVec<bool> pass(n, 0);

    for (size_t j = 0; j < n; ++j)
    {
        if (not (Jet_pt[j] >= 30.0f)) continue;
        if (not (std::fabs(Jet_eta[j]) <= 2.4f)) continue;
        if (not (Jet_jetId[j] >= 2)) continue;
        pass[j] = 1;
    }
    return pass;
};

std::vector<std::string> jet_2018ID_inputs =
{
    "Jet_pt",
    "Jet_eta",
    "Jet_jetId"
};

// ============================================================================
// GenParticle Filter
// ============================================================================
// ============================================================================
// GenParticle selection utilities (NanoAOD GenPart_* collection)
//
// Goal
//  1) Build a mask selecting particles that correspond (as closely as NanoAOD allows)
//     to the LHE hard-process record.
//  2) If a selected hard-process particle is W/Z/H/top/tau, also keep its full
//     decay tree as generated by Pythia (i.e. descendants), so you can read
//     W->cs, Z->bb, H->WW->..., H->ZZ->..., top->bW->..., tau decays, etc.
//  3) Return an RVec<bool> mask suitable for TrimCollection(..., maskCol, ...).
//
// Notes / assumptions
//  - NanoAOD does not store the LHE event record in GenPart; this uses GenPart
//    statusFlags to approximate "particles that would have been in LHE":
//      fromHardProcessBeforeFSR && isFirstCopy
//  - You can tune the "LHE-like" seed definition as needed.
// ============================================================================

inline auto gen_mask = [](const ROOT::VecOps::RVec<int>& pdgId,
                          const ROOT::VecOps::RVec<int>& status,
                          const ROOT::VecOps::RVec<int>& statusFlags,
                          const ROOT::VecOps::RVec<int>& genPartIdxMother) -> ROOT::VecOps::RVec<bool>
{
    using ROOT::VecOps::RVec;

    const size_t n = pdgId.size();
    RVec<bool> keep(n, false);
    if (n == 0) return keep;

    // status flags bit reader
    auto testBit = [](int flags, unsigned bit) -> bool {
        return (flags >> bit) & 0x1;
    };

    for (size_t i = 0; i < n; ++i)
    {
        const int s = status[i];
        const int p = pdgId[i];
        const int f = statusFlags[i];
        if (testBit(f, 7) and abs(p) <= 25) keep[i] = true;
        // std::cout <<  " s: " << s <<  " p: " << p <<  std::endl;
        // if (s == 21) keep[i] = true;
        // if (s == 23 and (abs(p) >= 11 and abs(p) <= 16)) keep[i] = true;
        // if (s == 23 and (abs(p) >= 1 and abs(p) <= 5)) keep[i] = true;
        // if (testBit(f, 8) and abs(p) <= 25) keep[i] = true;
        // if (s == 52) keep[i] = true;
        // keep[i] = true;
    }

    return keep;

};

inline std::vector<std::string> gen_mask_inputs =
{
    "GenPart_pdgId",
    "GenPart_status",
    "GenPart_statusFlags",
    "GenPart_genPartIdxMother"
};

inline auto lep_origin_mask = [](const ROOT::VecOps::RVec<int>& pdgId,
                                 const ROOT::VecOps::RVec<int>& genPartIdxMother) -> ROOT::VecOps::RVec<int>
{
    using ROOT::VecOps::RVec;
    const int n = (int)pdgId.size();
    RVec<int> code(n, -1);

    auto absId = [](int x){ return x < 0 ? -x : x; };

    // Minimal hadron-id helpers (PDG numbering conventions)
    auto isHadron = [&](int id)->bool { return absId(id) > 100; };

    auto hasDigit = [&](int id, int digit)->bool {
        id = absId(id);
        // PDG hadron codes carry quark content in decimal digits (works well for B/C tagging)
        // E.g. B mesons ~ 5xx, 5xxx; charm ~ 4xx, 4xxx; baryons similar.
        while (id > 0) { if (id % 10 == digit) return true; id /= 10; }
        return false;
    };

    auto isBeauty = [&](int id)->bool {
        const int a = absId(id);
        if (a == 5) return true;              // b quark
        if (!isHadron(a)) return false;
        return hasDigit(a, 5);                // any hadron containing b
    };

    auto isCharm = [&](int id)->bool {
        const int a = absId(id);
        if (a == 4) return true;              // c quark
        if (!isHadron(a)) return false;
        return hasDigit(a, 4);                // any hadron containing c
    };

    auto isLight = [&](int id)->bool {
        const int a = absId(id);
        // light quarks
        if (a >= 1 && a <= 3) return true;    // u,d,s
        // light hadrons (exclude b/c by construction)
        if (!isHadron(a)) return false;
        if (hasDigit(a, 4) || hasDigit(a, 5)) return false;
        return true;
    };

    for (int i = 0; i < n; ++i)
    {
        const int a = absId(pdgId[i]);
        if (!(a == 11 || a == 13)) continue; // classify only e/mu

        bool seenTau = false;
        int cur = i;

        // Walk up mother chain
        for (int steps = 0; steps < 100; ++steps)
        {
            const int mom = genPartIdxMother[cur];
            if (mom < 0 || mom >= n) break;

            const int mid = absId(pdgId[mom]);

            // tau encountered
            if (mid == 15) { seenTau = true; cur = mom; continue; }

            // W/Z encountered (tau flag decides which category)
            if (mid == 23) { code[i] = seenTau ? 2 : 0; break; }
            if (mid == 24) { code[i] = seenTau ? 3 : 1; break; }

            // Heavy/light flavor encountered (only if we haven't already labeled W/Z)
            if (isBeauty(pdgId[mom])) { code[i] = 5; break; }
            if (isCharm(pdgId[mom]))  { code[i] = 4; cur = mom; continue; }
            if (isLight(pdgId[mom]))  { code[i] = 6; break; }

            cur = mom;
        }
    }

    return code;
};

inline std::vector<std::string> lep_origin_mask_inputs =
{
    "GenPart_pdgId",
    "GenPart_genPartIdxMother"
};

// ==============================================================================






// -------------- ============ --------------------- ============ ---------------
// -------------- ============ --------------------- ============ ---------------
// -------------- ============ --------------------- ============ ---------------





// ============================================================================
// Object Properties Branches
// ============================================================================
inline std::vector<std::string> Muon_properties =
{
    "pt",
    "eta",
    "phi",
    "charge",
    "dxy",
    "dz",
    "sip3d",
    "miniPFRelIso_all"
};

inline std::vector<std::string> Electron_properties =
{
    "pt",
    "eta",
    "phi",
    "charge",
    "dxy",
    "dz",
    "sip3d",
    "miniPFRelIso_all"
};

inline std::vector<std::string> Jet_properties =
{
    "pt",
    "eta",
    "phi",
    "mass",
    "btagDeepFlavB"
};

inline std::vector<std::string> GenPart_properties =
{
    "pt",
    "eta",
    "phi",
    "mass",
    "pdgId",
    "status",
    "statusFlags",
    "genPartIdxMother",
    "lepOrigin",
};
// ==============================================================================






// -------------- ============ --------------------- ============ ---------------
// -------------- ============ --------------------- ============ ---------------
// -------------- ============ --------------------- ============ ---------------





// ==============================================================================
namespace RdfUtil
{

    // ============================================================================
    // Build a Good object collection from a NanoAOD style collection and a mask
    //
    // Purpose
    //   Create a filtered view of an object collection by applying a previously
    //   computed per object mask. The function defines new columns that follow
    //   a NanoAOD like naming convention such as
    //     GoodMuon_pt, GoodMuon_eta, GoodMuon_phi
    //   and also defines the corresponding multiplicity counter
    //     nGoodMuon
    //
    // Functional behavior
    //   For each requested branch suffix S in branchSuffixes
    //     outPrefix_S is defined as inPrefix_S[maskCol]
    //   and a counter nOutPrefix is defined as the number of true entries in maskCol
    //
    // Inputs
    //   inPrefix
    //     Collection prefix in the input tree such as Muon, Electron, Jet
    //
    //   maskCol
    //     Full name of the mask column such as Muon_2018LooseID
    //
    //   outPrefix
    //     Output collection prefix such as GoodMuon, GoodElectron, GoodJet
    //
    //   branchSuffixes
    //     List of branch suffixes to copy into the Good collection
    //
    // Outputs
    //   For each suffix S
    //     outPrefix_S
    //
    //   Counter
    //     nOutPrefix
    //
    // ============================================================================
    static RNode TrimCollection(RNode df,
                                const std::string& inPrefix,
                                const std::string& maskCol,
                                const std::string& outPrefix,
                                const std::vector<std::string>& branchSuffixes)
    {
        const std::string nOutCol = "n" + outPrefix;

        RNode out = df;

        for (std::size_t i = 0; i < branchSuffixes.size(); ++i)
        {
            const std::string& suf = branchSuffixes[i];

            const std::string inCol  = inPrefix + "_" + suf;
            const std::string outCol = outPrefix + "_" + suf;

            const std::string expr = inCol + "[" + maskCol + "]";
            out = out.Define(outCol, expr);
        }

        const std::string countExpr = "(int)Sum(" + maskCol + ")";
        out = out.Define(nOutCol, countExpr);

        return out;
    }


    // ============================================================================
    // Build a combined GoodLepton collection from GoodMuon and GoodElectron
    //
    // Purpose
    //   Merge previously built GoodMuon and GoodElectron collections into a single
    //   GoodLepton collection, sort by descending pt, and attach a per lepton pdgId
    //   consistent with charge and lepton flavor.
    //
    // Functional behavior
    //   For each event
    //     1) Concatenate GoodMuon and GoodElectron kinematics into one set
    //     2) Build pdgId using charge and flavor
    //        muon     pdgId = -13 if charge > 0 else +13
    //        electron pdgId = -11 if charge > 0 else +11
    //     3) Sort all leptons by pt in descending order
    //     4) Reorder all output branches consistently using the sort indices
    //     5) Define nGoodLepton following NanoAOD style naming
    //
    // Inputs
    //   GoodMuon_pt          RVec<float>
    //   GoodMuon_eta         RVec<float>
    //   GoodMuon_phi         RVec<float>
    //   GoodMuon_charge      RVec<int>
    //   GoodElectron_pt      RVec<float>
    //   GoodElectron_eta     RVec<float>
    //   GoodElectron_phi     RVec<float>
    //   GoodElectron_charge  RVec<int>
    //
    // Outputs
    //   GoodLepton_pt        RVec<float>
    //   GoodLepton_eta       RVec<float>
    //   GoodLepton_phi       RVec<float>
    //   GoodLepton_charge    RVec<int>
    //   GoodLepton_pdgId     RVec<int>
    //   GoodLepton_srcIdx    RVec<int>
    //   nGoodLepton          int
    //
    // Notes
    //   This helper assumes the GoodMuon and GoodElectron collections already exist
    //   and contain only leptons passing your intended IDs.
    // ============================================================================
    static RNode MergeCollections(RNode df,
                                  const std::string& goodObjectPrefix0,
                                  const std::string& goodObjectPrefix1,
                                  const std::string& outPrefix)
    {
        const std::string obj0_pt     = goodObjectPrefix0 + "_pt";
        const std::string obj0_eta    = goodObjectPrefix0 + "_eta";
        const std::string obj0_phi    = goodObjectPrefix0 + "_phi";
        const std::string obj0_charge = goodObjectPrefix0 + "_charge";

        const std::string obj1_pt     = goodObjectPrefix1 + "_pt";
        const std::string obj1_eta    = goodObjectPrefix1 + "_eta";
        const std::string obj1_phi    = goodObjectPrefix1 + "_phi";
        const std::string obj1_charge = goodObjectPrefix1 + "_charge";

        const std::string out_pt     = outPrefix + "_pt";
        const std::string out_eta    = outPrefix + "_eta";
        const std::string out_phi    = outPrefix + "_phi";
        const std::string out_charge = outPrefix + "_charge";
        const std::string out_pdgId  = outPrefix + "_pdgId";
        const std::string out_srcIdx = outPrefix + "_srcIdx";
        const std::string out_n      = "n" + outPrefix;

        const std::string carrier = "__" + outPrefix + "_carrier";

        struct GoodParticleCarrier {
            RVec<float> pt;
            RVec<float> eta;
            RVec<float> phi;
            RVec<int>   charge;
            RVec<int>   pdgId;
            RVec<int>   srcIdx;
        };

        RNode df1 =
            df.Define(
                carrier,
                [](const RVec<float>& Obj0_pt,
                   const RVec<float>& Obj0_eta,
                   const RVec<float>& Obj0_phi,
                   const RVec<int>&   Obj0_charge,
                   const RVec<float>& Obj1_pt,
                   const RVec<float>& Obj1_eta,
                   const RVec<float>& Obj1_phi,
                   const RVec<int>&   Obj1_charge) -> GoodParticleCarrier
                {
                    const size_t nobj0 = Obj0_pt.size();
                    const size_t nobj1 = Obj1_pt.size();
                    const size_t n     = nobj0 + nobj1;

                    GoodParticleCarrier out;
                    out.pt.resize(n);
                    out.eta.resize(n);
                    out.phi.resize(n);
                    out.charge.resize(n);
                    out.pdgId.resize(n);
                    out.srcIdx.resize(n);

                    size_t k = 0;

                    for (size_t i = 0; i < nobj0; ++i)
                    {
                        out.pt[k]     = Obj0_pt[i];
                        out.eta[k]    = Obj0_eta[i];
                        out.phi[k]    = Obj0_phi[i];
                        out.charge[k] = Obj0_charge[i];
                        out.srcIdx[k] = i;

                        const int q = (Obj0_charge[i] > 0.0f) ? +1 : -1;
                        out.pdgId[k] = (q > 0) ? -13 : +13;

                        ++k;
                    }

                    for (size_t i = 0; i < nobj1; ++i)
                    {
                        out.pt[k]     = Obj1_pt[i];
                        out.eta[k]    = Obj1_eta[i];
                        out.phi[k]    = Obj1_phi[i];
                        out.charge[k] = Obj1_charge[i];
                        out.srcIdx[k] = i;

                        const int q = (Obj1_charge[i] > 0.0f) ? +1 : -1;
                        out.pdgId[k] = (q > 0) ? -11 : +11;

                        ++k;
                    }

                    std::vector<size_t> idx(n);
                    for (size_t i = 0; i < n; ++i) idx[i] = i;

                    std::sort(idx.begin(), idx.end(),
                              [&out](size_t a, size_t b) { return out.pt[a] > out.pt[b]; });

                    GoodParticleCarrier sorted;
                    sorted.pt.resize(n);
                    sorted.eta.resize(n);
                    sorted.phi.resize(n);
                    sorted.charge.resize(n);
                    sorted.pdgId.resize(n);
                    sorted.srcIdx.resize(n);

                    for (size_t i = 0; i < n; ++i)
                    {
                        const size_t s = idx[i];
                        sorted.pt[i]     = out.pt[s];
                        sorted.eta[i]    = out.eta[s];
                        sorted.phi[i]    = out.phi[s];
                        sorted.charge[i] = out.charge[s];
                        sorted.pdgId[i]  = out.pdgId[s];
                        sorted.srcIdx[i] = out.srcIdx[s];
                    }

                    return sorted;
                },
                {obj0_pt, obj0_eta, obj0_phi, obj0_charge,
                    obj1_pt, obj1_eta, obj1_phi, obj1_charge});

        RNode df2 =
            df1.Define(out_pt    , [](const GoodParticleCarrier& c) -> RVec<float> { return c.pt; }, {carrier})
            .Define(out_eta   , [](const GoodParticleCarrier& c) -> RVec<float> { return c.eta; }, {carrier})
            .Define(out_phi   , [](const GoodParticleCarrier& c) -> RVec<float> { return c.phi; }, {carrier})
            .Define(out_charge, [](const GoodParticleCarrier& c) -> RVec<int> { return c.charge; }, {carrier})
            .Define(out_pdgId , [](const GoodParticleCarrier& c) -> RVec<int> { return c.pdgId; }, {carrier})
            .Define(out_srcIdx, [](const GoodParticleCarrier& c) -> RVec<int> { return c.srcIdx; }, {carrier})
            .Define(out_n     , [](const GoodParticleCarrier& c) -> int { return static_cast<int>(c.pt.size()); }, {carrier});

        return df2;
    }

    // ============================================================================
    // Overlap removal by deltaR against a reference collection
    //
    // Purpose
    //   Remove objects from a source collection if they overlap with any object in
    //   a reference collection within a configurable deltaR threshold. The output
    //   is a new collection containing only non overlapping objects and a NanoAOD
    //   style multiplicity counter.
    //
    // Functional behavior
    //   For each event, build a per object overlap mask for the source collection.
    //   A source object is rejected if there exists at least one reference object
    //   with deltaR(source, reference) < dR. The mask is then used to project the
    //   requested source branches into a new OR collection.
    //
    // Inputs
    //   Source collection columns
    //     srcPrefix_pt
    //     srcPrefix_eta
    //     srcPrefix_phi
    //   Reference collection columns
    //     refPrefix_eta
    //     refPrefix_phi
    //
    // Outputs
    //   A mask column
    //     outPrefix_ORmask
    //   A projected overlap removed collection
    //     outPrefix_suffix for each suffix in srcBranchSuffixes
    //   A multiplicity counter
    //     nOutPrefix
    //
    // Notes
    //   This helper is intended to be used after you have already created Good
    //   collections. It is generic for jets, leptons, photons, etc, as long as the
    //   collections use NanoAOD style eta and phi columns.
    // ============================================================================
    static RNode TrimCollectionByDeltaR(RNode df,
                                        const std::string& srcPrefix,
                                        const std::string& refPrefix,
                                        const std::string& outPrefix,
                                        const std::vector<std::string>& srcBranchSuffixes,
                                        const float dR)
    {
        const std::string srcEta = srcPrefix + "_eta";
        const std::string srcPhi = srcPrefix + "_phi";

        const std::string refEta = refPrefix + "_eta";
        const std::string refPhi = refPrefix + "_phi";

        const std::string maskCol = outPrefix + "_ORmask";

        const std::string nOutCol = "n" + outPrefix;

        // Build overlap mask for the source collection
        RNode df1 =
            df.Define(
                maskCol,
                [dR](const RVec<float>& sEta,
                     const RVec<float>& sPhi,
                     const RVec<float>& rEta,
                     const RVec<float>& rPhi) -> RVec<bool>
                {
                    const size_t ns = sEta.size();
                    const size_t nr = rEta.size();

                    RVec<bool> keep(ns, true);

                    for (size_t i = 0; i < ns; ++i)
                    {
                        bool overlaps = false;

                        for (size_t j = 0; j < nr; ++j)
                        {
                            LV p4_0(1, sEta[i], sPhi[i], 0);
                            LV p4_1(1, rEta[j], rPhi[j], 0);

                            float this_dr = ROOT::Math::VectorUtil::DeltaR(p4_0, p4_1);

                            if (this_dr < dR)
                            {
                                overlaps = true;
                                break;
                            }
                        }

                        if (overlaps) keep[i] = false;
                    }

                    return keep;
                },
                {srcEta, srcPhi, refEta, refPhi});

        // Project masked source branches into the overlap removed output collection
        RNode out = df1;

        for (std::size_t i = 0; i < srcBranchSuffixes.size(); ++i)
        {
            const std::string& suf = srcBranchSuffixes[i];

            const std::string inCol  = srcPrefix + "_" + suf;
            const std::string outCol = outPrefix + "_" + suf;

            const std::string expr = inCol + "[" + maskCol + "]";
            out = out.Define(outCol, expr);
        }

        // Define NanoAOD style multiplicity counter for the OR collection
        const std::string countExpr = "(int)Sum(" + maskCol + ")";
        out = out.Define(nOutCol, countExpr);

        return out;
    }

    // ===============================================================================
    //   Utility helpers for programmatic column selection in ROOT RDataFrame
    //   pipelines.
    // 
    //   Motivation:
    //     RDataFrame::Snapshot() does not support wildcard or glob-based column
    //     selection. This header provides a deterministic, zero-runtime-overhead
    //     mechanism to select Snapshot output columns using Unix-style glob patterns.
    // 
    //   Supported glob syntax:
    //       *    matches any number of characters (including zero)
    //       ?    matches exactly one character
    // 
    //   Features:
    //     - Include and exclude glob filters
    //     - Deterministic ordering
    //     - Thread-safe
    //     - No duplicates
    //     - Evaluated once at graph-construction time (no per-event cost)
    // 
    //   Example:
    //       auto cols = SelectColumnNames(df,
    //           { "GoodMuon_*", "GoodElectron_*", "GoodLepton_*", "MET_*" },
    //           { "*_ord", "*_srcIdx", "*_isMuon", "*_tmp*" });
    // 
    //       df.Snapshot("Events", "analysis.root", cols);
    // 
    // ===============================================================================


    inline std::regex GlobToRegex(const std::string& glob)
    {
        std::string r;
        r.reserve(glob.size() * 2);
        r.push_back('^');

        for (char c : glob) {
            switch (c) {
                case '*': r += ".*"; break;
                case '?': r += "."; break;
                case '.': case '\\': case '+': case '^': case '$':
                case '(': case ')': case '{': case '}': case '[': case ']':
                case '|':
                          r.push_back('\\'); r.push_back(c); break;
                default:
                          r.push_back(c);
            }
        }
        r.push_back('$');
        return std::regex(r, std::regex::ECMAScript);
    }


    inline std::vector<std::string> SelectColumnNames(ROOT::RDF::RNode df,
                                                               const std::vector<std::string>& include,
                                                               const std::vector<std::string>& exclude = {})
    {
        const auto all = df.GetColumnNames();

        std::vector<std::regex> inc, exc;
        for (auto& g : include) inc.emplace_back(GlobToRegex(g));
        for (auto& g : exclude) exc.emplace_back(GlobToRegex(g));

        std::vector<std::string> out;
        out.reserve(all.size());

        for (const auto& c : all) {
            bool keep = false;

            for (const auto& r : inc)
                if (std::regex_match(c, r)) { keep = true; break; }

            if (!keep) continue;

            for (const auto& r : exc)
                if (std::regex_match(c, r)) { keep = false; break; }

            if (keep) out.push_back(c);
        }

        return out;
    }


    // ============================================================================
    // MatchCollection: attach dr-match results to an existing collection
    //
    // Behavior
    //   - For each object, match to the closest target within dR < dRMax.
    //   - Always defines these three branches:
    //       objPrefix_tarPrefixIdx
    //       objPrefix_tarPrefixDr
    //
    // Inputs required
    //   objPrefix_eta, objPrefix_phi
    //   tarPrefix_eta, tarPrefix_phi
    //
    // Output indexing
    //   idx points into the target collection
    // ============================================================================
    static ROOT::RDF::RNode MatchCollection(ROOT::RDF::RNode df,
                                            const std::string& objPrefix,
                                            const std::string& tarPrefix,
                                            const float dRMax)
    {
        using ROOT::VecOps::RVec;

        // Named carrier type (must be visible to ROOT's type introspection)
        struct MatchCarrier
        {
            ROOT::VecOps::RVec<int>   idx;   // index into tarPrefix collection
            ROOT::VecOps::RVec<float> dr;    // best ΔR (inf if none)
        };

        std::string tarPrefixLowerFirst = tarPrefix;
        if (!tarPrefixLowerFirst.empty())
        {
            tarPrefixLowerFirst[0] = std::tolower(tarPrefixLowerFirst[0]);
        }

        const std::string obj_eta = objPrefix + "_eta";
        const std::string obj_phi = objPrefix + "_phi";

        const std::string tar_eta = tarPrefix + "_eta";
        const std::string tar_phi = tarPrefix + "_phi";

        const std::string carrier = "__" + objPrefix + "_" + tarPrefixLowerFirst + "MatchCarrier";

        const std::string out_idx = objPrefix + "_" + tarPrefixLowerFirst + "Idx";
        const std::string out_dr  = objPrefix + "_" + tarPrefixLowerFirst + "Dr";

        auto absId = [](int x) { return x < 0 ? -x : x; };

        // Build carrier (explicit types, explicit return type)
        df = df.Define(
            carrier,
            [dRMax, absId](const RVec<float>& oEta,
                           const RVec<float>& oPhi,
                           const RVec<float>& tEta,
                           const RVec<float>& tPhi) -> MatchCarrier
            {
                const size_t no = oEta.size();
                const size_t nt = tEta.size();

                MatchCarrier out;
                out.idx.assign(no, -1);
                out.dr.assign(no, std::numeric_limits<float>::infinity());

                for (size_t i = 0; i < no; ++i)
                {
                    float best = dRMax;
                    int bestIdx = -1;

                    LV p4o(1.0, oEta[i], oPhi[i], 0.0);

                    for (size_t j = 0; j < nt; ++j)
                    {
                        LV p4t(1.0, tEta[j], tPhi[j], 0.0);
                        const float dr = ROOT::Math::VectorUtil::DeltaR(p4o, p4t);

                        if (dr < best)
                        {
                            best = dr;
                            bestIdx = (int)j;
                        }
                    }

                    if (bestIdx >= 0)
                    {
                        out.idx[i]  = bestIdx;
                        out.dr[i]   = best;
                    }
                }

                return out;
            },
            {obj_eta, obj_phi, tar_eta, tar_phi}
        );

        // Unpack carrier (explicit lambdas; no generic lambdas)
        df = df.Define(out_idx, [](const MatchCarrier& c) -> RVec<int> { return c.idx; }, {carrier});
        df = df.Define(out_dr, [](const MatchCarrier& c) -> RVec<float> { return c.dr; }, {carrier});

        return df;
    }

    // ============================================================================
    // MonoCollection helper for ROOT RDataFrame
    //
    // Purpose
    //   Select the best single object from a NanoAOD style collection according to
    //   a user provided selector function.
    //
    // Summary
    //   For each event all objects i in the input collection are scanned. The
    //   selector receives one LV four vector and its index and returns a single
    //   float score. The best object is chosen by minimizing or maximizing that
    //   score.
    //
    // Selector convention
    //   selector(const LV& obj, int idx) -> float
    //
    //   The selector returns a finite score value for a valid object. If the
    //   selector returns NaN the object is rejected.
    //
    // Missing mass handling
    //   If prefix_mass does not exist in the dataframe, a zero mass column is
    //   created internally and used for four vector construction.
    //
    // Output branches
    //   out_prefixIdx1   index of selected object in prefix
    //   out_score        selected score value
    //   out_pt           selected object pt
    //   out_eta          selected object eta
    //   out_phi          selected object phi
    //   out_mass         selected object mass
    //
    // Typical use cases
    //   - Leading object tagging (maximize pt)
    //   - Closest to target mass object (minimize abs(m - target))
    //   - Best ID or quality object (maximize discriminator)
    //
    // ============================================================================

    enum OptMode
    {
        MinimizeScore,
        MaximizeScore
    };

    static bool ColumnExists(ROOT::RDF::RNode df, const std::string& name)
    {
        const auto cols = df.GetColumnNames();
        return std::find(cols.begin(), cols.end(), name) != cols.end();
    }

    struct MonoCarrier
    {
        int idx1;
        float score;

        float pt;
        float eta;
        float phi;
        float mass;
        float extra;
    };

    using MonoSelectorLV = std::function<float(const LV&, int, float)>;

    static ROOT::RDF::RNode MonoCollection(ROOT::RDF::RNode df,
                                           const std::string& prefix,
                                           const std::string& out,
                                           MonoSelectorLV selector,
                                           OptMode mode = MaximizeScore,
                                           const std::string& extra="")
    {
        std::string pt  = prefix + "_pt";
        std::string eta = prefix + "_eta";
        std::string phi = prefix + "_phi";
        std::string m   = prefix + "_mass";
        std::string ext = prefix + "_" + extra;

        // Missing mass handling
        if (!ColumnExists(df, m))
        {
            std::string tmp = "__" + prefix + "_mass0";
            if (!ColumnExists(df, tmp))
                df = df.Define(tmp,
                               [](const RVec<float>& v){ return RVec<float>(v.size(), 0.f); },
                               {pt});
            m = tmp;
        }

        // Missing extra column handling
        if (!ColumnExists(df, ext))
        {
            std::string tmp = "__" + prefix + "_extra0";
            if (!ColumnExists(df, tmp))
                df = df.Define(tmp,
                               [](const RVec<float>& v){ return RVec<float>(v.size(), 0.f); },
                               {pt});
            ext = tmp;
        }


        std::string carrier = "__" + out + "_monoCarrier";

        df = df.Define(
            carrier,
            [selector,mode](const RVec<float>& vpt,
                            const RVec<float>& veta,
                            const RVec<float>& vphi,
                            const RVec<float>& vm,
                            const RVec<float>& vext)
            {
                MonoCarrier best;
                best.idx1 = -1;

                float bestScore = (mode == MinimizeScore)
                    ? std::numeric_limits<float>::infinity()
                    : -std::numeric_limits<float>::infinity();
                best.score = bestScore;

                best.pt = 0.f;
                best.eta = 0.f;
                best.phi = 0.f;
                best.mass = 0.f;

                const size_t n = vpt.size();
                if (n == 0) return best;

                for (size_t i = 0; i < n; ++i)
                {
                    LV a(vpt[i], veta[i], vphi[i], vm[i]);

                    float score = selector(a, (int)i, vext[i]);
                    if (!std::isfinite(score)) continue;

                    bool take = (mode == MinimizeScore) ? (score < bestScore) : (score > bestScore);
                    if (!take) continue;

                    bestScore = score;

                    best.idx1 = (int)i;
                    best.score = score;

                    best.pt = (float)a.Pt();
                    best.eta = (float)a.Eta();
                    best.phi = (float)a.Phi();
                    best.mass = (float)a.M();
                }

                return best;
            },
            {pt, eta, phi, m, ext}
        );

        // Lowercase first letter prefix for index branch naming
        std::string plow = prefix;
        if (!plow.empty()) plow[0] = (char)std::tolower((unsigned char)plow[0]);

        df = df.Define(out + "_" + plow + "Idx1", [](const MonoCarrier& c){ return c.idx1;  }, {carrier});
        df = df.Define(out + "_score",           [](const MonoCarrier& c){ return c.score; }, {carrier});

        df = df.Define(out + "_pt",    [](const MonoCarrier& c){ return c.pt;    }, {carrier});
        df = df.Define(out + "_eta",   [](const MonoCarrier& c){ return c.eta;   }, {carrier});
        df = df.Define(out + "_phi",   [](const MonoCarrier& c){ return c.phi;   }, {carrier});
        df = df.Define(out + "_mass",  [](const MonoCarrier& c){ return c.mass;  }, {carrier});
        df = df.Define(out + "_extra", [](const MonoCarrier& c){ return c.extra; }, {carrier});

        return df;
    }



    // ============================================================================
    // PairCollection helper for ROOT RDataFrame
    //
    // Purpose
    //   Build the best object pair between two NanoAOD style collections according
    //   to a user provided selector function.
    //
    // Summary
    //   For each event all pairs (i,j) are scanned between collections p1 and p2.
    //   The selector receives two LV four vectors and their indices and returns a
    //   single float score. The best pair is chosen by minimizing or maximizing
    //   that score.
    //
    // Selector convention
    //   selector(const LV& obj1, const LV& obj2, int idx1, int idx2) -> float
    //
    //   The selector returns a finite score value for a valid pair. If the selector
    //   returns NaN the pair is rejected.
    //
    // Missing mass handling
    //   If p1_mass or p2_mass does not exist in the dataframe, a zero mass column
    //   is created internally and used for four vector construction.
    //
    // Pairing rules
    //   - If p1 and p2 are different collections, all (i,j) pairs are considered.
    //   - If p1 and p2 are the same collection, pairs with i == j are skipped.
    //   - Uniqueness constraints such as i < j can be enforced in the selector.
    //
    // Output branches
    //   out_idx1   index of first object in p1
    //   out_idx2   index of second object in p2
    //   out_score  selected score value
    //   out_mass   invariant mass of the selected pair
    //   out_dr     delta r between the two objects
    //   out_deta   delta eta between the two objects
    //   out_dphi   delta phi between the two objects
    //
    // Typical use cases
    //   - Closest object matching using minimum delta r
    //   - Z candidate selection using minimum mass difference
    //   - Dijet VBF like selection using maximum delta eta
    //   - Highest mass dijet selection
    //
    // ============================================================================ 

    struct PairCarrier
    {
        int idx1;
        int idx2;

        float score;

        float pt;
        float eta;
        float phi;
        float mass;
        float dr;
        float deta;
        float dphi;
    };

    using PairSelectorLV = std::function<float(const LV&, const LV&, int, int, float, float)>;

    static float RejectScore()
    {
        return std::numeric_limits<float>::quiet_NaN();
    }


    static PairSelectorLV selDr()
    {
        return [](const LV& a, const LV& b, int, int, float, float)
        {
            return (float) ROOT::Math::VectorUtil::DeltaR(a, b);
        };
    }

    static PairSelectorLV selAbsDeta()
    {
        return [](const LV& a, const LV& b, int, int, float, float)
        {
            return std::abs(a.Eta() - b.Eta());
        };
    }

    static PairSelectorLV selAbsDphi()
    {
        return [](const LV& a, const LV& b, int, int, float, float)
        {
            return (float) std::abs(ROOT::Math::VectorUtil::DeltaPhi(a, b));
        };
    }

    static PairSelectorLV selMass()
    {
        return [](const LV& a, const LV& b, int, int, float, float)
        {
            return (a + b).M();
        };
    }

    static PairSelectorLV selAbsMassDiff(float target)
    {
        return [target](const LV& a, const LV& b, int, int, float, float)
        {
            return std::abs((a + b).M() - target);
        };
    }

    static PairSelectorLV selDrWithPtMin(float ptMin1, float ptMin2)
    {
        return [ptMin1,ptMin2](const LV& a, const LV& b, int, int, float, float)
        {
            if (a.Pt() < ptMin1) return RejectScore();
            if (b.Pt() < ptMin2) return RejectScore();

            return (float) ROOT::Math::VectorUtil::DeltaR(a, b);
        };
    }

    static ROOT::RDF::RNode PairCollection(ROOT::RDF::RNode df,
                                           const std::string& p1,
                                           const std::string& p2,
                                           const std::string& out,
                                           PairSelectorLV selector,
                                           OptMode mode = MinimizeScore,
                                           const std::string& extra1="",
                                           const std::string& extra2="")
    {
        std::string p1pt  = p1 + "_pt";
        std::string p1eta = p1 + "_eta";
        std::string p1phi = p1 + "_phi";
        std::string p1m   = p1 + "_mass";
        std::string p1ext = p1 + "_" + extra1;

        std::string p2pt  = p2 + "_pt";
        std::string p2eta = p2 + "_eta";
        std::string p2phi = p2 + "_phi";
        std::string p2m   = p2 + "_mass";
        std::string p2ext = p2 + "_" + extra2;

        if (!ColumnExists(df, p1m))
        {
            std::string tmp1 = "__" + p1 + "_mass0";
            df = df.Define(tmp1, [](const RVec<float>& v){ return RVec<float>(v.size(), 0.f); }, {p1pt});
            p1m = tmp1;
        }

        if (!ColumnExists(df, p2m))
        {
            if (p2 == p1)
            {
                // same collection: reuse p1m (already real mass or temp mass0)
                p2m = p1m;
            }
            else
            {
                std::string tmp2 = "__" + p2 + "_mass0";
                if (!ColumnExists(df, tmp2))
                    df = df.Define(tmp2,
                                   [](const RVec<float>& v){ return RVec<float>(v.size(), 0.f); },
                                   {p2pt});
                p2m = tmp2;
            }
        }

        if (!ColumnExists(df, p1ext))
        {
            std::string tmp1 = "__" + p1 + "_extra0";
            df = df.Define(tmp1, [](const RVec<float>& v){ return RVec<float>(v.size(), 0.f); }, {p1pt});
            p1ext = tmp1;
        }

        if (!ColumnExists(df, p2ext))
        {
            if (p2 == p1)
            {
                // same collection: reuse p2ext (already real mass or temp mass0)
                p2ext = p1ext;
            }
            else
            {
                std::string tmp2 = "__" + p2 + "_extra0";
                if (!ColumnExists(df, tmp2))
                    df = df.Define(tmp2,
                                   [](const RVec<float>& v){ return RVec<float>(v.size(), 0.f); },
                                   {p2pt});
                p2ext = tmp2;
            }
        }

        std::string carrier = "__" + out + "_pairCarrier";

        df = df.Define(
            carrier,
            [selector,mode,p1,p2](const RVec<float>& pt1,
                                  const RVec<float>& eta1,
                                  const RVec<float>& phi1,
                                  const RVec<float>& m1,
                                  const RVec<float>& ext1,
                                  const RVec<float>& pt2,
                                  const RVec<float>& eta2,
                                  const RVec<float>& phi2,
                                  const RVec<float>& m2,
                                  const RVec<float>& ext2)
            {
                PairCarrier best;
                best.idx1  = -1;
                best.idx2  = -1;
                best.pt    = 0.f;
                best.eta   = std::numeric_limits<float>::infinity();
                best.phi   = 0.f;
                best.mass  = 0.f;
                best.dr    = std::numeric_limits<float>::infinity();
                best.deta  = 0.f;
                best.dphi  = 0.f;

                float bestScore = (mode == MinimizeScore)
                    ? std::numeric_limits<float>::infinity()
                    : -std::numeric_limits<float>::infinity();
                best.score = bestScore;

                // If the collection prefix is the same then
                // we flag it so that we don't consider same object pair
                bool same = (p1 == p2);

                // If nothing to consider then return empty
                const size_t n1 = pt1.size();
                const size_t n2 = pt2.size();
                if (n1 == 0 || n2 == 0)
                    return best;

                for (size_t i = 0; i < n1; ++i)
                {
                    for (size_t j = 0; j < n2; ++j)
                    {
                        // If same collection we skip when i == j
                        if (same && i == j) continue;

                        LV a(pt1[i], eta1[i], phi1[i], m1[i]);
                        LV b(pt2[j], eta2[j], phi2[j], m2[j]);

                        float score = selector(a, b, (int)i, (int)j, ext1[i], ext2[j]);
                        if (!std::isfinite(score)) continue;

                        bool take = (mode == MinimizeScore) ? (score < bestScore) : (score > bestScore);
                        if (!take) continue;

                        bestScore = score;

                        best.idx1  = (int)i;
                        best.idx2  = (int)j;
                        best.score = score;

                        LV pair = (a + b);
                        best.pt  = pair.Pt();
                        best.eta  = pair.Eta();
                        best.phi  = pair.Phi();
                        best.mass  = pair.M();

                        best.dr   = ROOT::Math::VectorUtil::DeltaR(a, b);
                        best.dphi = ROOT::Math::VectorUtil::DeltaPhi(a, b);
                        best.deta = a.Eta() - b.Eta();
                    }
                }

                return best;
            },
            {p1pt,p1eta,p1phi,p1m,p1ext,p2pt,p2eta,p2phi,p2m,p2ext}
        );

        // Lower case first letter prefix for out collection idx prefix
        std::string p1low = p1;
        if (!p1low.empty())
        {
            p1low[0] = std::tolower(p1low[0]);
        }

        std::string p2low = p2;
        if (!p2low.empty())
        {
            p2low[0] = std::tolower(p2low[0]);
        }

        df = df.Define(out + "_" + p1low + "Idx1",  [](const PairCarrier& c){ return c.idx1;  }, {carrier});
        df = df.Define(out + "_" + p2low + "Idx2",  [](const PairCarrier& c){ return c.idx2;  }, {carrier});
        df = df.Define(out + "_score", [](const PairCarrier& c){ return c.score; }, {carrier});

        df = df.Define(out + "_pt",    [](const PairCarrier& c){ return c.pt;   }, {carrier});
        df = df.Define(out + "_eta",   [](const PairCarrier& c){ return c.eta;  }, {carrier});
        df = df.Define(out + "_phi",   [](const PairCarrier& c){ return c.phi;  }, {carrier});
        df = df.Define(out + "_mass",  [](const PairCarrier& c){ return c.mass; }, {carrier});
        df = df.Define(out + "_dr",    [](const PairCarrier& c){ return c.dr;   }, {carrier});
        df = df.Define(out + "_deta",  [](const PairCarrier& c){ return c.deta; }, {carrier});
        df = df.Define(out + "_dphi",  [](const PairCarrier& c){ return c.dphi; }, {carrier});

        return df;
    }







    // ============================================================================
    // TrioCollection helper for ROOT RDataFrame
    //
    // Purpose
    //   Build the best object trio between three NanoAOD style collections according
    //   to a user provided selector function.
    //
    // Summary
    //   For each event all triples (i,j,k) are scanned between collections c1, c2
    //   and c3. The selector receives three LV four vectors and their indices and
    //   returns a single float score. The best trio is chosen by minimizing or
    //   maximizing that score.
    //
    // Selector convention
    //   selector(const LV& obj1, const LV& obj2, const LV& obj3,
    //            int idx1, int idx2, int idx3) -> float
    //
    //   The selector returns a finite score value for a valid trio. If the selector
    //   returns NaN the trio is rejected.
    //
    // Missing mass handling
    //   If c1_mass, c2_mass or c3_mass does not exist in the dataframe, a zero mass
    //   column is created internally and used for four vector construction.
    //
    // Trio rules
    //   - If c1, c2 and c3 are different collections, all (i,j,k) triples are considered.
    //   - If any two of c1, c2 and c3 are the same collection, triples with repeated
    //     indices for that collection are skipped.
    //   - Uniqueness constraints such as i < j < k can be enforced in the selector.
    //
    // Output branches
    //   out_c1Idx1   index of first object in c1
    //   out_c2Idx2   index of second object in c2
    //   out_c3Idx3   index of third object in c3
    //   out_score    selected score value
    //   out_mass     invariant mass of the selected trio
    //   out_sumPt    sum of transverse momenta of the trio
    //   out_dr12     delta r between object 1 and object 2
    //   out_dr13     delta r between object 1 and object 3
    //   out_dr23     delta r between object 2 and object 3
    //   out_minDr    minimum pairwise delta r within the trio
    //   out_maxDr    maximum pairwise delta r within the trio
    //
    // Typical use cases
    //   - Three jet resonance reconstruction using maximum invariant mass
    //   - Tight three object cluster selection using minimum delta r
    //   - Multi lepton candidate building using mass window matching
    //
    // ============================================================================


    struct TrioCarrier
    {
        int idx1;
        int idx2;
        int idx3;

        float score;

        float pt;
        float eta;
        float phi;
        float mass;

        float dr12;
        float dr13;
        float dr23;

        float minDr;
        float maxDr;
    };

    using TrioSelectorLV = std::function<float(const LV&, const LV&, const LV&, int, int, int, float, float, float)>;

    static TrioSelectorLV selTrioMass()
    {
        return [](const LV& a, const LV& b, const LV& c, int, int, int, float, float, float) -> float
        {
            return (float)(a + b + c).M();
        };
    }

    static TrioSelectorLV selTrioAbsMassDiff(float target)
    {
        return [target](const LV& a, const LV& b, const LV& c, int, int, int, float, float, float) -> float
        {
            return (float)std::abs((a + b + c).M() - (double)target);
        };
    }

    static TrioSelectorLV selTrioMinDr()
    {
        return [](const LV& a, const LV& b, const LV& c, int, int, int, float, float, float) -> float
        {
            const double dr12 = ROOT::Math::VectorUtil::DeltaR(a, b);
            const double dr13 = ROOT::Math::VectorUtil::DeltaR(a, c);
            const double dr23 = ROOT::Math::VectorUtil::DeltaR(b, c);
            return (float)std::min(dr12, std::min(dr13, dr23));
        };
    }

    static TrioSelectorLV selTrioMaxDr()
    {
        return [](const LV& a, const LV& b, const LV& c, int, int, int, float, float, float) -> float
        {
            const double dr12 = ROOT::Math::VectorUtil::DeltaR(a, b);
            const double dr13 = ROOT::Math::VectorUtil::DeltaR(a, c);
            const double dr23 = ROOT::Math::VectorUtil::DeltaR(b, c);
            return (float)std::max(dr12, std::max(dr13, dr23));
        };
    }

    static TrioSelectorLV selTrioSumPt()
    {
        return [](const LV& a, const LV& b, const LV& c, int, int, int, float, float, float) -> float
        {
            return (float)(a.Pt() + b.Pt() + c.Pt());
        };
    }

    static TrioSelectorLV selTrioMassWithPtMin(float ptMin1, float ptMin2, float ptMin3)
    {
        return [ptMin1,ptMin2,ptMin3](const LV& a, const LV& b, const LV& c, int, int, int, float, float, float) -> float
        {
            if (a.Pt() < ptMin1) return RejectScore();
            if (b.Pt() < ptMin2) return RejectScore();
            if (c.Pt() < ptMin3) return RejectScore();
            return (float)(a + b + c).M();
        };
    }


    static std::string LowerFirst(const std::string& s)
    {
        if (s.empty()) return s;
        std::string r = s;
        r[0] = (char)std::tolower((unsigned char)r[0]);
        return r;
    }

    static ROOT::RDF::RNode TrioCollection(ROOT::RDF::RNode df,
                                           const std::string& c1,
                                           const std::string& c2,
                                           const std::string& c3,
                                           const std::string& out,
                                           TrioSelectorLV selector,
                                           OptMode mode = MinimizeScore,
                                           const std::string& ext1="",
                                           const std::string& ext2="",
                                           const std::string& ext3="")
    {
        std::string c1pt  = c1 + "_pt";
        std::string c1eta = c1 + "_eta";
        std::string c1phi = c1 + "_phi";
        std::string c1m   = c1 + "_mass";
        std::string c1ext = c1 + "_" + ext1;

        std::string c2pt  = c2 + "_pt";
        std::string c2eta = c2 + "_eta";
        std::string c2phi = c2 + "_phi";
        std::string c2m   = c2 + "_mass";
        std::string c2ext = c2 + "_" + ext2;

        std::string c3pt  = c3 + "_pt";
        std::string c3eta = c3 + "_eta";
        std::string c3phi = c3 + "_phi";
        std::string c3m   = c3 + "_mass";
        std::string c3ext = c3 + "_" + ext3;

        // Missing mass handling with safe reuse when collection names collide
        if (!ColumnExists(df, c1m))
        {
            std::string tmp = "__" + c1 + "_mass0";
            if (!ColumnExists(df, tmp))
                df = df.Define(tmp, [](const RVec<float>& v){ return RVec<float>(v.size(), 0.f); }, {c1pt});
            c1m = tmp;
        }

        if (!ColumnExists(df, c2m))
        {
            if (c2 == c1) c2m = c1m;
            else
            {
                std::string tmp = "__" + c2 + "_mass0";
                if (!ColumnExists(df, tmp))
                    df = df.Define(tmp, [](const RVec<float>& v){ return RVec<float>(v.size(), 0.f); }, {c2pt});
                c2m = tmp;
            }
        }

        if (!ColumnExists(df, c3m))
        {
            if (c3 == c1) c3m = c1m;
            else if (c3 == c2) c3m = c2m;
            else
            {
                std::string tmp = "__" + c3 + "_mass0";
                if (!ColumnExists(df, tmp))
                    df = df.Define(tmp, [](const RVec<float>& v){ return RVec<float>(v.size(), 0.f); }, {c3pt});
                c3m = tmp;
            }
        }

        // Missing mass handling with safe reuse when collection names collide
        if (!ColumnExists(df, c1ext))
        {
            std::string tmp = "__" + c1 + "_mass0";
            if (!ColumnExists(df, tmp))
                df = df.Define(tmp, [](const RVec<float>& v){ return RVec<float>(v.size(), 0.f); }, {c1pt});
            c1ext = tmp;
        }

        if (!ColumnExists(df, c2ext))
        {
            if (c2 == c1) c2ext = c1ext;
            else
            {
                std::string tmp = "__" + c2 + "_mass0";
                if (!ColumnExists(df, tmp))
                    df = df.Define(tmp, [](const RVec<float>& v){ return RVec<float>(v.size(), 0.f); }, {c2pt});
                c2ext = tmp;
            }
        }

        if (!ColumnExists(df, c3ext))
        {
            if (c3 == c1) c3ext = c1ext;
            else if (c3 == c2) c3ext = c2ext;
            else
            {
                std::string tmp = "__" + c3 + "_mass0";
                if (!ColumnExists(df, tmp))
                    df = df.Define(tmp, [](const RVec<float>& v){ return RVec<float>(v.size(), 0.f); }, {c3pt});
                c3ext = tmp;
            }
        }

        std::string carrier = "__" + out + "_trioCarrier";

        df = df.Define(
            carrier,
            [selector,mode,c1,c2,c3](const RVec<float>& pt1,
                                     const RVec<float>& eta1,
                                     const RVec<float>& phi1,
                                     const RVec<float>& m1,
                                     const RVec<float>& vext1,
                                     const RVec<float>& pt2,
                                     const RVec<float>& eta2,
                                     const RVec<float>& phi2,
                                     const RVec<float>& m2,
                                     const RVec<float>& vext2,
                                     const RVec<float>& pt3,
                                     const RVec<float>& eta3,
                                     const RVec<float>& phi3,
                                     const RVec<float>& m3,
                                     const RVec<float>& vext3)
            {
                TrioCarrier best;
                best.idx1 = -1;
                best.idx2 = -1;
                best.idx3 = -1;

                float bestScore = (mode == MinimizeScore)
                    ? std::numeric_limits<float>::infinity()
                    : -std::numeric_limits<float>::infinity();

                best.score = bestScore;

                best.pt = 0.f;
                best.eta = std::numeric_limits<float>::infinity();
                best.phi = 0.f;
                best.mass = 0.f;

                best.dr12 = std::numeric_limits<float>::infinity();
                best.dr13 = std::numeric_limits<float>::infinity();
                best.dr23 = std::numeric_limits<float>::infinity();

                best.minDr = std::numeric_limits<float>::infinity();
                best.maxDr = 0.f;

                const bool same12 = (c1 == c2);
                const bool same13 = (c1 == c3);
                const bool same23 = (c2 == c3);

                const size_t n1 = pt1.size();
                const size_t n2 = pt2.size();
                const size_t n3 = pt3.size();
                if (n1 == 0 || n2 == 0 || n3 == 0) return best;

                for (size_t i = 0; i < n1; ++i)
                {
                    for (size_t j = 0; j < n2; ++j)
                    {
                        for (size_t k = 0; k < n3; ++k)
                        {
                            if (same12 && i == j) continue;
                            if (same13 && i == k) continue;
                            if (same23 && j == k) continue;

                            LV a(pt1[i], eta1[i], phi1[i], m1[i]);
                            LV b(pt2[j], eta2[j], phi2[j], m2[j]);
                            LV c(pt3[k], eta3[k], phi3[k], m3[k]);

                            float score = selector(a, b, c, (int)i, (int)j, (int)k, vext1[i], vext2[j], vext3[k]);
                            if (!std::isfinite(score)) continue;

                            bool take = (mode == MinimizeScore) ? (score < bestScore) : (score > bestScore);
                            if (!take) continue;

                            bestScore = score;

                            best.idx1 = (int)i;
                            best.idx2 = (int)j;
                            best.idx3 = (int)k;

                            best.score = score;

                            LV trio = (a + b + c);
                            best.pt = (float)trio.Pt();
                            best.eta = (float)trio.Eta();
                            best.phi = (float)trio.Phi();
                            best.mass = (float)trio.M();

                            const double dr12 = ROOT::Math::VectorUtil::DeltaR(a, b);
                            const double dr13 = ROOT::Math::VectorUtil::DeltaR(a, c);
                            const double dr23 = ROOT::Math::VectorUtil::DeltaR(b, c);

                            best.dr12 = (float)dr12;
                            best.dr13 = (float)dr13;
                            best.dr23 = (float)dr23;

                            const float minDr = (float)std::min(dr12, std::min(dr13, dr23));
                            const float maxDr = (float)std::max(dr12, std::max(dr13, dr23));

                            best.minDr = minDr;
                            best.maxDr = maxDr;
                        }
                    }
                }

                return best;
            },
            {c1pt,c1eta,c1phi,c1m,c1ext,c2pt,c2eta,c2phi,c2m,c2ext,c3pt,c3eta,c3phi,c3m,c3ext}
        );

        std::string c1low = LowerFirst(c1);
        std::string c2low = LowerFirst(c2);
        std::string c3low = LowerFirst(c3);

        df = df.Define(out + "_" + c1low + "Idx1", [](const TrioCarrier& t){ return t.idx1; }, {carrier});
        df = df.Define(out + "_" + c2low + "Idx2", [](const TrioCarrier& t){ return t.idx2; }, {carrier});
        df = df.Define(out + "_" + c3low + "Idx3", [](const TrioCarrier& t){ return t.idx3; }, {carrier});

        df = df.Define(out + "_score", [](const TrioCarrier& t){ return t.score; }, {carrier});

        df = df.Define(out + "_pt",    [](const TrioCarrier& t){ return t.pt;   }, {carrier});
        df = df.Define(out + "_eta",   [](const TrioCarrier& t){ return t.eta;  }, {carrier});
        df = df.Define(out + "_phi",   [](const TrioCarrier& t){ return t.phi;  }, {carrier});
        df = df.Define(out + "_mass",  [](const TrioCarrier& t){ return t.mass; }, {carrier});

        df = df.Define(out + "_dr12",  [](const TrioCarrier& t){ return t.dr12; }, {carrier});
        df = df.Define(out + "_dr13",  [](const TrioCarrier& t){ return t.dr13; }, {carrier});
        df = df.Define(out + "_dr23",  [](const TrioCarrier& t){ return t.dr23; }, {carrier});

        df = df.Define(out + "_minDr", [](const TrioCarrier& t){ return t.minDr; }, {carrier});
        df = df.Define(out + "_maxDr", [](const TrioCarrier& t){ return t.maxDr; }, {carrier});

        return df;
    }


}



